/**
 * 노래방 인기차트 TOP 100 (앱 내장 데이터)
 * 최근 히트곡 + 노래방 스테디셀러를 섞은 애창곡 차트.
 * 노래방 기기 번호는 기기/버전마다 다르므로 포함하지 않음 —
 * 내 노래에 담은 뒤 직접 번호를 적어둘 수 있어요.
 */
const CHART_TOP100 = [
  { rank: 1,   title: "APT.", artist: "로제(ROSÉ) & Bruno Mars", genre: "댄스", year: 2024 },
  { rank: 2,   title: "나는 반딧불", artist: "황가람", genre: "발라드", year: 2024 },
  { rank: 3,   title: "비의 랩소디", artist: "임재현", genre: "발라드", year: 2023 },
  { rank: 4,   title: "헤어지자 말해요", artist: "박재정", genre: "발라드", year: 2023 },
  { rank: 5,   title: "고민중독", artist: "QWER", genre: "락/밴드", year: 2024 },
  { rank: 6,   title: "밤양갱", artist: "비비(BIBI)", genre: "발라드", year: 2024 },
  { rank: 7,   title: "소나기", artist: "이클립스(ECLIPSE)", genre: "OST", year: 2024 },
  { rank: 8,   title: "첫 만남은 계획대로 되지 않아", artist: "TWS(투어스)", genre: "댄스", year: 2024 },
  { rank: 9,   title: "Magnetic", artist: "아일릿(ILLIT)", genre: "댄스", year: 2024 },
  { rank: 10,  title: "Supernova", artist: "aespa", genre: "댄스", year: 2024 },
  { rank: 11,  title: "테스형!", artist: "나훈아", genre: "트로트", year: 2020 },
  { rank: 12,  title: "해야 (HEYA)", artist: "IVE", genre: "댄스", year: 2024 },
  { rank: 13,  title: "나는 아픈 건 딱 질색이니까", artist: "(여자)아이들", genre: "댄스", year: 2024 },
  { rank: 14,  title: "Love wins all", artist: "아이유", genre: "발라드", year: 2024 },
  { rank: 15,  title: "Seven", artist: "정국 (feat. Latto)", genre: "댄스", year: 2023 },
  { rank: 16,  title: "퀸카 (Queencard)", artist: "(여자)아이들", genre: "댄스", year: 2023 },
  { rank: 17,  title: "I AM", artist: "IVE", genre: "댄스", year: 2023 },
  { rank: 18,  title: "Ditto", artist: "NewJeans", genre: "댄스", year: 2022 },
  { rank: 19,  title: "Hype Boy", artist: "NewJeans", genre: "댄스", year: 2022 },
  { rank: 20,  title: "손오공", artist: "세븐틴", genre: "댄스", year: 2023 },
  { rank: 21,  title: "Love Lee", artist: "AKMU(악뮤)", genre: "팝", year: 2023 },
  { rank: 22,  title: "어머나", artist: "장윤정", genre: "트로트", year: 2004 },
  { rank: 23,  title: "인사", artist: "범진", genre: "발라드", year: 2023 },
  { rank: 24,  title: "사건의 지평선", artist: "윤하", genre: "락/밴드", year: 2022 },
  { rank: 25,  title: "Welcome to the Show", artist: "DAY6(데이식스)", genre: "락/밴드", year: 2024 },
  { rank: 26,  title: "한 페이지가 될 수 있게", artist: "DAY6(데이식스)", genre: "락/밴드", year: 2019 },
  { rank: 27,  title: "예뻤어", artist: "DAY6(데이식스)", genre: "락/밴드", year: 2017 },
  { rank: 28,  title: "신호등", artist: "이무진", genre: "발라드", year: 2021 },
  { rank: 29,  title: "사랑인가 봐", artist: "멜로망스", genre: "발라드", year: 2022 },
  { rank: 30,  title: "취중고백", artist: "김민석", genre: "발라드", year: 2021 },
  { rank: 31,  title: "사랑은 늘 도망가", artist: "임영웅", genre: "트로트", year: 2021 },
  { rank: 32,  title: "다시 만날 수 있을까", artist: "임영웅", genre: "발라드", year: 2022 },
  { rank: 33,  title: "취기를 빌려", artist: "산들", genre: "발라드", year: 2020 },
  { rank: 34,  title: "어떻게 지내", artist: "크러쉬(Crush)", genre: "R&B", year: 2020 },
  { rank: 35,  title: "다정히 내 이름을 부르면", artist: "경서예지·전건호", genre: "발라드", year: 2021 },
  { rank: 36,  title: "밤하늘의 별을", artist: "경서", genre: "발라드", year: 2020 },
  { rank: 37,  title: "Celebrity", artist: "아이유", genre: "팝", year: 2021 },
  { rank: 38,  title: "라일락", artist: "아이유", genre: "팝", year: 2021 },
  { rank: 39,  title: "아무노래", artist: "지코(ZICO)", genre: "힙합", year: 2020 },
  { rank: 40,  title: "롤린 (Rollin')", artist: "브레이브걸스", genre: "댄스", year: 2017 },
  { rank: 41,  title: "다시 여기 바닷가", artist: "싹쓰리", genre: "댄스", year: 2020 },
  { rank: 42,  title: "Dynamite", artist: "방탄소년단(BTS)", genre: "댄스", year: 2020 },
  { rank: 43,  title: "TOMBOY", artist: "(여자)아이들", genre: "댄스", year: 2022 },
  { rank: 44,  title: "어떻게 이별까지 사랑하겠어, 널 사랑하는 거지", artist: "AKMU(악뮤)", genre: "발라드", year: 2019 },
  { rank: 45,  title: "오랜 날 오랜 밤", artist: "AKMU(악뮤)", genre: "포크/인디", year: 2017 },
  { rank: 46,  title: "주저하는 연인들을 위해", artist: "잔나비", genre: "락/밴드", year: 2019 },
  { rank: 47,  title: "모든 날, 모든 순간", artist: "폴킴", genre: "발라드", year: 2018 },
  { rank: 48,  title: "너를 만나", artist: "폴킴", genre: "발라드", year: 2017 },
  { rank: 49,  title: "그날처럼", artist: "장덕철", genre: "발라드", year: 2018 },
  { rank: 50,  title: "사랑에 연습이 있었다면", artist: "임재현", genre: "발라드", year: 2019 },
  { rank: 51,  title: "좋니", artist: "윤종신", genre: "발라드", year: 2017 },
  { rank: 52,  title: "선물", artist: "멜로망스", genre: "발라드", year: 2017 },
  { rank: 53,  title: "비도 오고 그래서", artist: "헤이즈 (feat. 신용재)", genre: "R&B", year: 2017 },
  { rank: 54,  title: "첫눈처럼 너에게 가겠다", artist: "에일리", genre: "OST", year: 2017 },
  { rank: 55,  title: "Beautiful", artist: "크러쉬(Crush)", genre: "OST", year: 2016 },
  { rank: 56,  title: "우주를 줄게", artist: "볼빨간사춘기", genre: "포크/인디", year: 2016 },
  { rank: 57,  title: "여행", artist: "볼빨간사춘기", genre: "포크/인디", year: 2018 },
  { rank: 58,  title: "사랑을 했다", artist: "iKON", genre: "댄스", year: 2018 },
  { rank: 59,  title: "봄날", artist: "방탄소년단(BTS)", genre: "댄스", year: 2017 },
  { rank: 60,  title: "METEOR", artist: "창모", genre: "힙합", year: 2019 },
  { rank: 61,  title: "이 노래가 클럽에서 나온다면", artist: "우디(Woody)", genre: "발라드", year: 2019 },
  { rank: 62,  title: "어디에도", artist: "엠씨더맥스", genre: "발라드", year: 2016 },
  { rank: 63,  title: "밤편지", artist: "아이유", genre: "발라드", year: 2017 },
  { rank: 64,  title: "Blueming", artist: "아이유", genre: "팝", year: 2019 },
  { rank: 65,  title: "마지막처럼", artist: "블랙핑크", genre: "댄스", year: 2017 },
  { rank: 66,  title: "TT", artist: "트와이스", genre: "댄스", year: 2016 },
  { rank: 67,  title: "너의 모든 순간", artist: "성시경", genre: "OST", year: 2014 },
  { rank: 68,  title: "내가 저지른 사랑", artist: "임창정", genre: "발라드", year: 2017 },
  { rank: 69,  title: "걱정말아요 그대", artist: "이적", genre: "발라드", year: 2015 },
  { rank: 70,  title: "벚꽃 엔딩", artist: "버스커버스커", genre: "포크/인디", year: 2012 },
  { rank: 71,  title: "여수 밤바다", artist: "버스커버스커", genre: "포크/인디", year: 2012 },
  { rank: 72,  title: "좋은 날", artist: "아이유", genre: "팝", year: 2010 },
  { rank: 73,  title: "너랑 나", artist: "아이유", genre: "팝", year: 2011 },
  { rank: 74,  title: "스물다섯, 스물하나", artist: "자우림", genre: "락/밴드", year: 2013 },
  { rank: 75,  title: "야생화", artist: "박효신", genre: "발라드", year: 2014 },
  { rank: 76,  title: "바람기억", artist: "나얼", genre: "R&B", year: 2012 },
  { rank: 77,  title: "봄 사랑 벚꽃 말고", artist: "HIGH4·아이유", genre: "팝", year: 2014 },
  { rank: 78,  title: "이러지마 제발", artist: "케이윌", genre: "발라드", year: 2012 },
  { rank: 79,  title: "안녕이라고 말하지마", artist: "다비치", genre: "발라드", year: 2011 },
  { rank: 80,  title: "고백 (Go Back)", artist: "다이나믹 듀오", genre: "힙합", year: 2011 },
  { rank: 81,  title: "내가 제일 잘 나가", artist: "2NE1", genre: "댄스", year: 2011 },
  { rank: 82,  title: "삐딱하게", artist: "G-DRAGON", genre: "힙합", year: 2013 },
  { rank: 83,  title: "말하는 대로", artist: "처진 달팽이(유재석·이적)", genre: "포크/인디", year: 2011 },
  { rank: 84,  title: "눈의 꽃", artist: "박효신", genre: "발라드", year: 2004 },
  { rank: 85,  title: "보고 싶다", artist: "김범수", genre: "발라드", year: 2002 },
  { rank: 86,  title: "벌써 일년", artist: "브라운아이즈", genre: "R&B", year: 2001 },
  { rank: 87,  title: "I Believe", artist: "신승훈", genre: "발라드", year: 2001 },
  { rank: 88,  title: "To Heaven", artist: "조성모", genre: "발라드", year: 1998 },
  { rank: 89,  title: "총 맞은 것처럼", artist: "백지영", genre: "발라드", year: 2008 },
  { rank: 90,  title: "거리에서", artist: "성시경", genre: "발라드", year: 2006 },
  { rank: 91,  title: "소주 한 잔", artist: "임창정", genre: "발라드", year: 2003 },
  { rank: 92,  title: "겁쟁이", artist: "버즈", genre: "락/밴드", year: 2005 },
  { rank: 93,  title: "가시", artist: "버즈", genre: "락/밴드", year: 2003 },
  { rank: 94,  title: "너를 위해", artist: "임재범", genre: "발라드", year: 2000 },
  { rank: 95,  title: "고해", artist: "임재범", genre: "발라드", year: 1998 },
  { rank: 96,  title: "응급실", artist: "izi(이지)", genre: "락/밴드", year: 2005 },
  { rank: 97,  title: "체념", artist: "빅마마", genre: "발라드", year: 2003 },
  { rank: 98,  title: "Tears", artist: "소찬휘", genre: "락/밴드", year: 2000 },
  { rank: 99,  title: "하루하루", artist: "빅뱅", genre: "댄스", year: 2008 },
  { rank: 100, title: "거짓말", artist: "빅뱅", genre: "댄스", year: 2007 },
];

// 추가 스테디셀러 — 차트엔 안 보이지만 "둘 다" 뽑기 풀을 넓히고 싶을 때를 대비한 예비 목록.
// 현재 버전에서는 CHART_TOP100만 사용하지만, 데이터 확장 시 여기에 곡을 옮겨 담으면 된다.
const CHART_EXTRA = [
  { title: "사랑했나봐", artist: "윤도현", genre: "발라드", year: 2005 },
  { title: "나는 나비", artist: "YB", genre: "락/밴드", year: 2006 },
  { title: "잘못된 만남", artist: "김건모", genre: "댄스", year: 1995 },
  { title: "챔피언", artist: "싸이(PSY)", genre: "댄스", year: 2002 },
  { title: "낭만고양이", artist: "체리필터", genre: "락/밴드", year: 2002 },
  { title: "매직 카펫 라이드", artist: "자우림", genre: "락/밴드", year: 2000 },
  { title: "넌 내게 반했어", artist: "노브레인", genre: "락/밴드", year: 2005 },
  { title: "Y (Please Tell Me Why)", artist: "프리스타일", genre: "힙합", year: 2004 },
  { title: "사랑합니다", artist: "팀(Tim)", genre: "발라드", year: 2003 },
  { title: "안 되나요", artist: "휘성", genre: "R&B", year: 2004 },
  { title: "친구라도 될 걸 그랬어", artist: "거미", genre: "R&B", year: 2004 },
  { title: "거짓말", artist: "god", genre: "발라드", year: 2000 },
  { title: "라라라", artist: "SG워너비", genre: "발라드", year: 2008 },
  { title: "Timeless", artist: "SG워너비", genre: "발라드", year: 2004 },
  { title: "사랑앓이", artist: "FT아일랜드", genre: "락/밴드", year: 2007 },
  { title: "거위의 꿈", artist: "인순이", genre: "발라드", year: 2007 },
  { title: "서른 즈음에", artist: "김광석", genre: "포크/인디", year: 1994 },
  { title: "사랑했지만", artist: "김광석", genre: "포크/인디", year: 1991 },
  { title: "무조건", artist: "박상철", genre: "트로트", year: 2005 },
  { title: "Whiplash", artist: "aespa", genre: "댄스", year: 2024 },
  { title: "Love 119", artist: "RIIZE", genre: "댄스", year: 2024 },
  { title: "안동역에서", artist: "진성", genre: "트로트", year: 2012 },
  { title: "애상", artist: "쿨", genre: "댄스", year: 1998 },
];
